$include:
  - configs/online/online_prefix_decoder/online_prefix_decoder_base.yml

OnlinePrefixDecoderTransformerMultiOut.future_visibility: 0
OnlinePrefixDecoderTransformerMultiOut.chunk_length: 50


